### ISSUE TITLE
Cannot compile on Ubuntu 17.10

### ISSUE THREAD

**Issue by malikolivier** [OpenSpace/OpenSpace#599]
Hi, I tried to compile OpenSpace on the `master` branch, then on the `beta/beta-1_2` tag, with no success. I get the same error. I run linux (Ubuntu 17.10) with cmake version 3.9.1 and gcc 7.2.0. Here is the content of the error:

```
/home/malik/workspace/veille/c++/OpenSpace/ext/sgct/src/deps/vrpn/vrpn_Connection.C: In function 'int vrpn_start_server(const char*, char*, char*, const char*)':
/home/malik/workspace/veille/c++/OpenSpace/ext/sgct/src/deps/vrpn/vrpn_Connection.C:2492:24: error: aggregate 'vrpn_start_server(const char*, char*, char*, const char*)::wait status' has incomplete type and cannot be defined
             union wait status;
                        ^~~~~~
ext/sgct/src/deps/vrpn/CMakeFiles/vrpn.dir/build.make:182: recipe for target 'ext/sgct/src/deps/vrpn/CMakeFiles/vrpn.dir/vrpn_Connection.C.o' failed
make[2]: *** [ext/sgct/src/deps/vrpn/CMakeFiles/vrpn.dir/vrpn_Connection.C.o] Error 1
CMakeFiles/Makefile2:2007: recipe for target 'ext/sgct/src/deps/vrpn/CMakeFiles/vrpn.dir/all' failed
make[1]: *** [ext/sgct/src/deps/vrpn/CMakeFiles/vrpn.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

It seems that `union wait` from `<sys/wait.h>` has been deprecated (since the early 90s) and is now removed from glibc. It was removed in glibc 2.25. [1] My system uses 2.26.So I replaced `union wait` by `int` as it should be, then I get another error:

```
In file included from /home/malik/workspace/veille/c++/OpenSpace/ext/sgct/src/sgct/MessageHandler.cpp:12:0:
/home/malik/workspace/veille/c++/OpenSpace/ext/sgct/include/sgct/helpers/SGCTPortedFunctions.h: In function 'int vswcprintf(const wchar_t*, __va_list_tag*)':
/home/malik/workspace/veille/c++/OpenSpace/ext/sgct/include/sgct/helpers/SGCTPortedFunctions.h:32:11: error: 'vsnwprintf' was not declared in this scope
  retval = vsnwprintf(NULL, 0, format, argcopy);
```

I see that the missing function's string is found in some DLLs as follows:

```
malik@XPS-13-9360:~/workspace/veille/c++/OpenSpace$ grep "vsnwprintf"  -r .
Binary file ./modules/globebrowsing/ext/gdal/lib/gdal202.dll matches
./ext/sgct/include/sgct/helpers/SGCTPortedFunctions.h:    retval = vsnwprintf(NULL, 0, format, argcopy);
Binary file ./ext/curl/lib/libeay32.dll matches
```

Is it a GNU/Linux specific issue? I have read the compilation manual for Linux there: https://github.com/OpenSpace/OpenSpace/wiki/Guides-Compile-OpenSpace-on-Linux.

[1] https://sourceware.org/ml/libc-alpha/2016-02/msg00342.html

**Comment by jon-grangien** [comment]
You probably moved on by now but as a Linux user I suggest to just use Windows or Mac if it is available as they are leading platforms at this point in development. Personally I don't know if it is a Linux specific issue or if Windows and Mac simply don't use glibc 2.26+ at this time, but I run on Ubuntu 16.04 with glibc 2.23 installed don't get the error on the latest master.

Otherwise, I cannot look into SGCT but if you'd decide to downgrade glibc there are some other quirks with Linux support that I can post here.

**Comment by malikolivier** [comment]
Thanks for your answer.

I can downgrade glibc and retry. Would you let me know what are the other quirks with Linux support? The [README](https://github.com/OpenSpace/OpenSpace/blob/e13160efb51c610ec155f0dcdbda705e2df50a95/README.md) says that there is Linux support, so I expected it be compilable without quirks.

I can try to help out with a few PRs for Linux support if it is not too hard.

**Comment by alexanderbock** [comment]
That would be very appreciated.  The compilation on Linux should work without quirks (and we need to look into the problems with the new glibc), since it is being compiled on Ubuntu every night.
We do not have many Linux users yet, so while running, there might be platform-specific bugs that we haven't caught yet.

**Comment by malikolivier** [comment]
@alexanderbock Thanks.

> The compilation on Linux should work without quirks (and we need to look into the problems with the new glibc), since it is being compiled on Ubuntu every night.

Are you testing on Ubuntu 16.04? By the way, the new LTS 18.04, which most probably ships glibc 2.26+ is out.

> Otherwise, I cannot look into SGCT but if you'd decide to downgrade glibc there are some other quirks with Linux support that I can post here.

@jon-grangien was hinting at some quirks on Linux. So I guess it was about uncaught platform-specific bugs, right?

**Comment by jon-grangien** [comment]
One quirk is that there has been a problem with how textures are read and displayed by the libraries FreeImage and SOIL. Recently stb_image was added which works well on Linux but needs to be placed first in the order of active image readers to have an effect. It is done [in this commit](https://github.com/OpenSpace/OpenSpace/commit/00b37aaf0a33930b4fcd1c1fb95a7bd61cffa694) but it is not in master, @alexanderbock can say if it is okay to have it first in the order or if it could be handled as an edge case for Linux. To use it you have to check the flag `GHOUL_USE_STB_IMAGE`

Then, globe browsing (Google earth-like planetary mapping at different levels) does not work on Linux probably because of issues with how the GDAL library works. You should be able to turn off globe browsing and have a simple texture for the planets by unchecking the flag `OPENSPACE_MODULE_GLOBEBROWSING` but then you have to edit the assets files so that the scene in use does not make use of any globe browsing code. I haven't done that so I can't help with that unfortunately.

I think it's just those two.

**Comment by malikolivier** [comment]
I tried to build on Ubuntu 16.04 with cmake version 3.11.1, gcc 7.3.0 and glibc 2.23.

I hit another problem when compiling glm (a ghoul dependency).
It seems the version of glm used in OpenSpace does not support gcc 7.3.0. [1]

However gcc 7.3 support is already fixed upstream, so the bug should be fixable by updating glm.

Or you using gcc 7.1.0 on your test machine?

[1] https://github.com/g-truc/glm/issues/726

**Comment by malikolivier** [comment]
I just compiled gcc-7.1 from sources and I get yet *another* error with gcc-7.1.

```

**Comment by jon-grangien** [comment]
Personally I have gcc 7.2 :)

**Comment by alexanderbock** [comment]
Sorry for dropping this;

@malikolivier  The error looks indeed weird since `ghoul::MissingCaseException` is an empty struct, so it should be constexpr constructable‽

Here is the output from our Jenkins build machines, it's also 7.2 @ Ubuntu 16.04:
```
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-1ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.0 (Ubuntu 7.2.0-1ubuntu1~16.04)
```

**Comment by alexanderbock** [comment]
Closed due to inactivity

**Comment by swealex** [comment]
I get a similar error:

[ 12%] Building CXX object ext/ghoul/CMakeFiles/Ghoul.dir/src/io/volume/rawvolumereader.cpp.o
In file included from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_int.hpp:6:0,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/fwd.hpp:6,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/glm.hpp:61,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/glm.h:58,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/io/volume/rawvolumereader.h:31,
                 from /home/alexander/OpenSpace/ext/ghoul/src/io/volume/rawvolumereader.cpp:26:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/setup.hpp:456:100: note: #pragma message: GLM: GCC older than 4.6 has a bug presenting the use of rgba and stpq components
 : GCC older than 4.6 has a bug presenting the use of rgba and stpq components")
                                                                               ^
In file included from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4.inl:968:0,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4.hpp:453,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/vec4.hpp:6,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/glm.hpp:70,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/glm.h:58,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/io/volume/rawvolumereader.h:31,
                 from /home/alexander/OpenSpace/ext/ghoul/src/io/volume/rawvolumereader.cpp:26:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In static member function ‘static glm::tvec4<float, (glm::precision)5> glm::detail::compute_vec4_div<float, (glm::precision)5, true>::call(const glm::tvec4<float, (glm::precision)5>&, const glm::tvec4<float, (glm::precision)5>&)’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:156:11: error: ‘struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
           ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:156:31: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
                               ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:156:50: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
                                                  ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)5]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:367:3: error: class ‘glm::tvec4<float, (glm::precision)5>’ does not have any field named ‘data’
   data(_mm_set1_ps(s))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)4]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:372:3: error: class ‘glm::tvec4<float, (glm::precision)4>’ does not have any field named ‘data’
   data(_mm_set1_ps(s))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)3]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:377:3: error: class ‘glm::tvec4<float, (glm::precision)3>’ does not have any field named ‘data’
   data(_mm_set1_ps(s))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = int; glm::precision P = (glm::precision)5]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:399:3: error: class ‘glm::tvec4<int, (glm::precision)5>’ does not have any field named ‘data’
   data(_mm_set1_epi32(s))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = int; glm::precision P = (glm::precision)4]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:404:3: error: class ‘glm::tvec4<int, (glm::precision)4>’ does not have any field named ‘data’
   data(_mm_set1_epi32(s))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = int; glm::precision P = (glm::precision)3]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:409:3: error: class ‘glm::tvec4<int, (glm::precision)3>’ does not have any field named ‘data’
   data(_mm_set1_epi32(s))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T, T, T, T) [with T = float; glm::precision P = (glm::precision)5]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:431:3: error: class ‘glm::tvec4<float, (glm::precision)5>’ does not have any field named ‘data’
   data(_mm_set_ps(d, c, b, a))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T, T, T, T) [with T = float; glm::precision P = (glm::precision)4]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:436:3: error: class ‘glm::tvec4<float, (glm::precision)4>’ does not have any field named ‘data’
   data(_mm_set_ps(d, c, b, a))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T, T, T, T) [with T = float; glm::precision P = (glm::precision)3]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:441:3: error: class ‘glm::tvec4<float, (glm::precision)3>’ does not have any field named ‘data’
   data(_mm_set_ps(d, c, b, a))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = int; glm::precision P = (glm::precision)5]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:447:3: error: class ‘glm::tvec4<int, (glm::precision)5>’ does not have any field named ‘data’
   data(_mm_set_epi32(d, c, b, a))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = int; glm::precision P = (glm::precision)4]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:453:3: error: class ‘glm::tvec4<int, (glm::precision)4>’ does not have any field named ‘data’
   data(_mm_set_epi32(d, c, b, a))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = int; glm::precision P = (glm::precision)3]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:459:3: error: class ‘glm::tvec4<int, (glm::precision)3>’ does not have any field named ‘data’
   data(_mm_set_epi32(d, c, b, a))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = float; glm::precision P = (glm::precision)5]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:465:3: error: class ‘glm::tvec4<float, (glm::precision)5>’ does not have any field named ‘data’
   data(_mm_castsi128_ps(_mm_set_epi32(d, c, b, a)))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = float; glm::precision P = (glm::precision)4]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:471:3: error: class ‘glm::tvec4<float, (glm::precision)4>’ does not have any field named ‘data’
   data(_mm_castsi128_ps(_mm_set_epi32(d, c, b, a)))
   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = float; glm::precision P = (glm::precision)3]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:477:3: error: class ‘glm::tvec4<float, (glm::precision)3>’ does not have any field named ‘data’
   data(_mm_castsi128_ps(_mm_set_epi32(d, c, b, a)))
   ^~~~
In file included from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_exponential.inl:144:0,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_exponential.hpp:103,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_geometric.inl:4,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_geometric.hpp:113,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/geometric.hpp:6,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix.inl:4,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix.hpp:149,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_mat2x2.inl:4,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_mat2x2.hpp:182,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/mat2x2.hpp:6,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/glm.hpp:71,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/glm.h:58,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/io/volume/rawvolumereader.h:31,
                 from /home/alexander/OpenSpace/ext/ghoul/src/io/volume/rawvolumereader.cpp:26:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_exponential_simd.inl: In static member function ‘static glm::tvec4<float, (glm::precision)5> glm::detail::compute_sqrt<glm::tvec4, float, (glm::precision)5, true>::call(const glm::tvec4<float, (glm::precision)5>&)’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_exponential_simd.inl:28:11: error: ‘struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    result.data = glm_vec4_sqrt_lowp(v.data);
           ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_exponential_simd.inl:28:39: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    result.data = glm_vec4_sqrt_lowp(v.data);
                                       ^~~~
In file included from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix.inl:399:0,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix.hpp:149,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_mat2x2.inl:4,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_mat2x2.hpp:182,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/mat2x2.hpp:6,
                 from /home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/glm.hpp:71,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/glm.h:58,
                 from /home/alexander/OpenSpace/ext/ghoul/include/ghoul/io/volume/rawvolumereader.h:31,
                 from /home/alexander/OpenSpace/ext/ghoul/src/io/volume/rawvolumereader.cpp:26:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl: In function ‘typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type glm::outerProduct(const vecTypeA<T, P>&, const vecTypeB<T, P>&) [with T = float; glm::precision P = (glm::precision)5; vecTypeA = glm::tvec4; vecTypeB = glm::tvec4; typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type = glm::tmat4x4<float, (glm::precision)5>]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:67:27: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                           ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:67:35: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:67:79: error: ‘glm::tmat4x4<float, (glm::precision)5>::col_type {aka struct glm::tvec4<float, (glm::precision)5>}’ has no member named ‘data’
 mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                                                         ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl: In function ‘typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type glm::outerProduct(const vecTypeA<T, P>&, const vecTypeB<T, P>&) [with T = float; glm::precision P = (glm::precision)4; vecTypeA = glm::tvec4; vecTypeB = glm::tvec4; typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type = glm::tmat4x4<float, (glm::precision)4>]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:75:27: error: ‘const struct glm::tvec4<float, (glm::precision)4>’ has no member named ‘data’
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                           ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:75:35: error: ‘const struct glm::tvec4<float, (glm::precision)4>’ has no member named ‘data’
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:75:79: error: ‘glm::tmat4x4<float, (glm::precision)4>::col_type {aka struct glm::tvec4<float, (glm::precision)4>}’ has no member named ‘data’
 mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                                                         ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl: In function ‘typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type glm::outerProduct(const vecTypeA<T, P>&, const vecTypeB<T, P>&) [with T = float; glm::precision P = (glm::precision)3; vecTypeA = glm::tvec4; vecTypeB = glm::tvec4; typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type = glm::tmat4x4<float, (glm::precision)3>]’:
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:83:27: error: ‘const struct glm::tvec4<float, (glm::precision)3>’ has no member named ‘data’
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                           ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:83:35: error: ‘const struct glm::tvec4<float, (glm::precision)3>’ has no member named ‘data’
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                   ^~~~
/home/alexander/OpenSpace/ext/ghoul/ext/glm/glm/detail/func_matrix_simd.inl:83:79: error: ‘glm::tmat4x4<float, (glm::precision)3>::col_type {aka struct glm::tvec4<float, (glm::precision)3>}’ has no member named ‘data’
 mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                                                         ^~~~
ext/ghoul/CMakeFiles/Ghoul.dir/build.make:374: recipe for target 'ext/ghoul/CMakeFiles/Ghoul.dir/src/io/volume/rawvolumereader.cpp.o' failed
make[2]: *** [ext/ghoul/CMakeFiles/Ghoul.dir/src/io/volume/rawvolumereader.cpp.o] Error 1
CMakeFiles/Makefile2:252: recipe for target 'ext/ghoul/CMakeFiles/Ghoul.dir/all' failed
make[1]: *** [ext/ghoul/CMakeFiles/Ghoul.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by GPayne** [comment]
Master branch builds successfully in Ubuntu 18.04, with gcc 8.2 (gcc needs to be upgraded beyond what 18.04 installs by default). See issue #791.
