### ISSUE TITLE
Build error on Ubuntu: rawvolumereader.cpp.... no member named data

### ISSUE THREAD

**Issue by nealmcb** [OpenSpace/OpenSpace#791]
I'm trying to build OpenSpace for the first time, on Ubuntu Linux 18.04 LTS Bionic.
In addition to the libraries named in [compiling Ubuntu OpenSpace Wiki](http://wiki.openspaceproject.com/developer/compiling/ubuntu)
I did `sudo apt-get install libsoil1 libglew2.0 freeglut3-dev` to make `cmake` happy.
When running make, I got part way thru, but failed with this error:

```
[ 17%] Building CXX object ext/ghoul/CMakeFiles/Ghoul.dir/src/io/volume/rawvolumereader.cpp.o
...
/srv/s/astro/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl: In static member function
 static glm::tvec4<float, (glm::precision)5> glm::detail::compute_vec4_div<float,
  (glm::precision)5, true>::call(const glm::tvec4<float, (glm::precision)5>&,
 const glm::tvec4<float, (glm::precision)5>&):
/srv/s/astro/OpenSpace/ext/ghoul/ext/glm/glm/detail/type_vec4_simd.inl:156:11:
 error: struct glm::tvec4<float, (glm::precision)5> has no member named data
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
...
```
There were lots more `no member named data` errors after that.

I also got some pragma notes about GCC older than 4.6, but I'm running `gcc 7.3.0` and `cmake 3.10.2`. so they don't seem relevant.

**Comment by nealmcb** [comment]
This looks relevant: [Update glm version to fix build with GCC 7.3](https://github.com/g-truc/glm/issues/726)

**Comment by alexanderbock** [comment]
Also see this:
https://github.com/OpenSpace/OpenSpace/issues/779

There are two issues that were preventing us from using a newer GLM version

**Comment by elehcim** [comment]
I managed to compile on ubuntu 18.04.2 using gcc-8.

The binary `GhoulTest` passes all the 100 tests.
`OpenspaceTest` instead fails on:

```
$ ./OpenSpaceTest 
TransformationManager (Warning) : Kameleon module needed for transformations with dynamic frames
Lua (Debug) : Creating Lua state
Lua (Debug) : Open libraries
Lua (Debug) : Creating Lua state
Lua (Debug) : Open libraries
[==========] Running 233 tests from 13 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from AssetLoaderTest
[ RUN      ] AssetLoaderTest.Assertions
ScriptEngine (Debug) : Adding base library
ScriptEngine (Debug) : Initializing Lua state
ScriptEngine (Debug) : Create openspace base library
ScriptEngine (Debug) : Add OpenSpace modules

    File:       OpenSpace/ext/ghoul/src/filesystem/filesystem.cpp, line 149
    Function:   static ghoul::filesystem::FileSystem& ghoul::filesystem::FileSystem::ref()
    Assertion:  isInitialized()    FileSystem is not initialized

```

Launching OpenSpace I had an OpenGL issue which I overcome overriding the GL version.

```
$ MESA_GL_VERSION_OVERRIDE=4.5 MESA_GLSL_VERSION_OVERRIDE=450 ./OpenSpace
```

**Comment by nealmcb** [comment]
Thanks, @elehcim. Very helpful!

After the compiler and GL version override, did OpenSpace work?
Did the OpenSpaceTest error seem to have any other effects?
What graphics card/driver was this with?

Was that on master? What commit?

**Comment by elehcim** [comment]
Hi @nealmcb,
Yes OpenSpace starts, after the splash screen (the first time it has to download many files, so it took 5' on my laptop downloading @ 100Mbit/s), I can see the rendering of the Milky way and the solar system. I have a problem though: the whole scene is contiuously rotating in an errating way. The mouse controls don't seem to work. I tried other scenes changing the "asset" in openspace.cfg without success. I don't know what the problem is.

I can stop the rendered scene from rotating if from the WebGUI I disable `Use keyframe interaction` from `Settings -> NavigationHandler`.

I'm sorry, I am an OpenSpace newbie, I've still to understand how to use it, I was stuck in the compilation phase ;)  (I only have GNU/Linux OS available). I don't know if the OpenSpaceTest error has other effects.

I built on master at commit: a1a1ee71dbdc506bf692f774016123dc70e10d75

I have `Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)`

```
$ glxinfo |grep "OpenGL"
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.2.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
